### PR TITLE
Flake8 and other clean-ups

### PR DESCRIPTION
**Pull request by hvelarde**

### CODE REVIEW

**Comment by hvelarde** [comment]
@keul could you please help me reviewing this and finishing the Flake8 stuff?

**Comment by keul** [comment]
Yep! I just need some times to look at this (maybe tomorrow?)

**Comment by keul** [comment]
@hvelarde you want to reach a full flake8 format? I see only E501 (line too long errors) there.

**Comment by hvelarde** [comment]
@keul there are no E501 reported in Travis (I always ignore them):

```bash
$ bin/code-analysis
Deprecated aliases...................[ OK ] in 0.040s
JSHint...............................[ OK ] in 0.034s
Check clean lines....................[ OK ] in 0.162s
CSS Lint.............................[ OK ] in 0.306s
Flake8..........................[ FAILURE ] in 0.595s
/home/travis/build/collective/collective.portlet.calendar/collective/portlet/calendar/tests/test_calendarex.py:320:48: Q000 Remove Double quotes.
/home/travis/build/collective/collective.portlet.calendar/collective/portlet/calendar/calendar.py:105:19: Q000 Remove Double quotes.
/home/travis/build/collective/collective.portlet.calendar/collective/portlet/calendar/calendar.py:262:1: C901 'Renderer.getEventsForCalendar' is too complex (14)
```

I don't know if the issue are worth to fix.

**Comment by keul** [comment]
@hvelarde sorry, looked in wrong place. I'll fix this

**Comment by keul** [comment]
@hvelarde forgot to ping you, but I've done here

**Comment by hvelarde** [comment]
great, thanks!

**Pull request merged**
